name: "Tests"

on:
  pull_request:
    branches:
      - main

jobs:
  py_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions/img_converter
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover -s ./tests
  php_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions/ogp_extractor
    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl
          tools: composer
      - name: Install dependencies
        run: composer install
      - name: Run tests
        run: composer test
